---
title: "Launchbook jQuery"
type: "challenge"
description: "Practice manipulating the DOM with jQuery."
visibility: "assign"
tags: "jquery, dom"
ignore:
- "public/"
- "views/"
- "app.rb"
- "Gemfile"
- "Gemfile.lock"
- "launchbook-jquery.md"
